meta_product_name: "meetU"
meta_title: "meetU - Connect with strangers"
meta_description: "The easiest way to organize events for free with strangers wherever you go. Connect with strangers, live new experiences! Meet new people with the same interest than you and search free activities in town"
meta_image: "meetU_logo.png" # should exist in `app/assets/images/`
